autoscaling:
  enabled: false
cert:
  manager:
    namespace: cert-manager
    version: v1.16.1
deployment:
  enabled: true
image:
  pullPolicy: IfNotPresent
  repository: monokal/tinyproxy
ingress:
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    cert-manager.io/cluster-issuer: jiangsier-tinyproxy-letsencrypt-http01
  className: nginx
  enabled: false
  hosts:
    - host: ''
      paths:
        - path: /
          pathType: Prefix
  tls:
    enabled: true
pdb:
  create: true
  minAvailable: ''
  maxUnavailable: ''
replicaCount: 1
resources:
  limits: {}
  requests: {}
service:
  type: LoadBalancer
  port: 8888
serviceAccount:
  create: true
  automount: false
livenessProbe:
  tcpSocket:
    port: 8888
readinessProbe:
  tcpSocket:
    port: 8888


